### ISSUE TITLE
Launching to the Ecliptic (for interplanetary transfers)

### ISSUE THREAD

**Issue by TheGrover** [Noiredd/PEGAS#11]
Currently the program allows targeting for the moon or other spacecraft orbiting Earth, but has no support for launching to a parking orbit in preparation for an interplanetary transfer.

Not knowing how to set up the inclination and LAN myself, is it possible for a mission file to be created for such an orbit?

**Comment by Noiredd** [comment]
Short answer: no, it is not possible and is very likely to never be possible.

Designing an interplanetary transfer and a parking orbit for it is a complex task in a **mission planning** domain. PEGAS however is merely a **launch guidance** tool - its primary assumption is that you know what you're driving and where you're going. Yes it does have a functionality of launching to a reference target, but it is not mission design - notice that it doesn't let you do things like like Apollo free return trajectory. It's just a way of saying: *I know where I'm going: it's the same plane as this thing*, a little convenience function so that you don't have to spend time looking up inclination in LAN (which KSP doesn't even tell you) and retyping them into the `mission` file.

I will not agree that PEGAS "has no support for launching to a parking orbit in preparation for an interplanetary transfer". It only has no support for *designing* this orbit - which is way outside its scope as a guidance tool anyway. Think of PEGAS as a piece of software installed in the rocket itself: it does only what the mission planning department wants. And the mission planning department has its computers and algorithms [elsewhere](http://ksp.olex.biz/) ;)

Warning: no one will stop you from selecting, say, Mars as your target, and running a mission with incomplete information (which will be filled by simply reading the target's parameters). But what's going to happen in this case will be far from what you want. Since Mars orbits the Sun, the parameters that will be pulled will be in a Sun-centric frame. There's no check whether the target actually orbits the Earth\*, so PEGAS will never know it's a Sun-centric and not Earth\*-centric frame, and will blindly attempt to launch into a completely meaningless orbit.  
\* - replace "Earth" with any body that you're launching from (PEGAS is not constrained to Earth launch sites)
