### ISSUE TITLE
Too many infinite loops

### ISSUE THREAD

**Issue by mferrie** [Noiredd/PEGAS#2]
Instead of using "until false...break" loops, it is a much better programming practice to use proper "until <condition>" loops. Not only that, but it saves memory by not making the computer constantly create and delete the same process repeatedly.

**Comment by Noiredd** [comment]
Please link to a piece of code where you think this is the issue?

**Comment by mferrie** [comment]
From the main file:

UNTIL FALSE {
	//	check how much time to countdown end
	SET cdTN TO cdT0 - TIME:SECONDS.
	//	if we're past the timestamp of the current event
	IF cdTN < cdEvents[cdId] {
		//	if we're at the ignition event - stage
		IF cdId = cdIgnite {
			PRINT "IGNITION!".
			LOCK THROTTLE TO 1.
			STAGE.	//	Be aware that this should not be allowed to happen too quickly, as the stage might not be ready right after loading the vehicle and physics
		}
		//	else means to just print a message
		ELSE {
			CLEARSCREEN.
			PRINT "Countdown... " + cdEvents[cdId].
		}.
		//	increment position on the events list
		SET cdId TO cdId+1.
		//	and if we're out of events - exit the loop
		IF cdId = cdEvents:LENGTH { BREAK. }.
	}.
	WAIT 0.
}.
UNTIL FALSE {
	SET P_time TO TIME:SECONDS - P_t0.
	getState(P_engines).	//	update state variables
	//	recalculate steering vector
	SET P_pitch TO 90-getPitch(MIN(P_time,P_seq[3]-S_krTime)).	//	stop pitching at the last moments before cutoff - rocket must not rotate for safe separation
	SET P_steer TO LOOKDIRUP(HEADING(90,P_pitch):VECTOR, SHIP:FACING:TOPVECTOR).	//	TODO: FIXED AZIMUTH MUST BE MOVED TO SETTINGS
	//	data outputs
	dataViz().
	IF S_logging = 1 { dataLog(P_logfn). }.
	//	sequence control: should the boosters be jettisoned?
	IF P_seq[1]>0 {
		//	the following assumes boosters will not be jettisoned milliseconds into the flight, and the stage will be ready in any reallistic scenario
		IF P_time>P_seq[1] AND F_boosters = 0 {
			addMessage("BOOSTERS JETTISONED!").
			SET F_boosters TO 1.
			STAGE.
		}.
	}.
	//	sequence control: should the fairings be jettisoned?
	IF P_seq[2]>0 {
		IF P_time>P_seq[2] AND F_fairings = 0 {
			addMessage("FAIRINGS JETTISONED!").
			SET F_fairings TO 1.
			STAGE.
		}.
	}.
	//	TODO: consider replacing constant checks with a single WHEN for both events
	//	exit check
	IF P_time>P_seq[3] BREAK.
	WAIT 0.2.
}.

**Comment by Noiredd** [comment]
You're partially right: the first `UNTIL` loop could use a condition `cdId = cdEvents:LENGTH` to be more clear. Second could probably be similarly structured.
To the best of my knowledge however, you are not right about "computer constantly creating and deleting the same process". In compiled languages (and kOS is _kind of_ a compiled language) loop is just a few conditional jump instructions, not separate processes that the program needs to spawn. A condition check is executed anyway, no matter what condition you specify, a `FALSE` or `IF cdId = something` and none is faster than the other (in fact, just a `FALSE` could actually be faster, but I don't know the details of kOS ML). The only speed increase comes from the fact that the current code does two checks: first the loop termination condition, then the additional `IF` near the end that _actually_ terminates it. As for memory increase, are you certain that kOS interpreter (compiler) needs more memory the way I've written my loops? If that's the case, please point me to some reading on the matter - I don't claim to be an expert on kOS.
In any case, I'm closing this issue, since this code will be removed from the repository soon anyway.
