### ISSUE TITLE
some problems 

### ISSUE THREAD

**Issue by GYskyfall** [Noiredd/PEGAS#25]
In the negative guidance program, the spacecraft will keep the attack angle zero. However, when I was running the program, the angle of the spacecraft pitch over too fast and pitch over about 90 degrees at the altitude of 20km. would you like to tell me how to fix it?

**Comment by GYskyfall** [comment]
i think i had fixed the problem. it may be related to speed and altitude.
i think it's better to use the MJ's algorithm in nagetive guidance.

**Comment by Noiredd** [comment]
Would you mind giving some details about the craft that you're using? For each stage, what is the initial TWR, burn time, Isp? When do you engage the UPFG phase and what is the velocity and altitude at that point?

You have to know that much of the algorithm's performance depends on the settings, sometimes it is difficult to pick them right.

**Comment by GYskyfall** [comment]
After the rocket took off, if the speed and altitude do not reach a certain value and they pitch, the rocket will reduce the pitch angle to 0 too quickly, causing the launch to fail.At the beginning I didn't realize this, I was pitched too early, and it led to failure

**Comment by GYskyfall** [comment]
Maybe you can use the Mechjeb2 model during  guidance

**Comment by GYskyfall** [comment]
Maybe you can use the Mechjeb2 model during negative guidance

**Comment by GYskyfall** [comment]
If you switch to another spacecraft while using Pegas, Pegas will not work properly. For example, if you want to reclaim the first stage booster, after switching to the first stage booster, the second stagel will not be able to work properly. Pegas will report an error and cannot read the parameters properly.

**Comment by GYskyfall** [comment]
It is difficult to hit the GTO orbit with pegas, and pegas does not support secondary multiple ignition. This is important for missions

**Comment by Noiredd** [comment]
Yeah you're observing the typical behavior of UPFG - if the passive part of the ascent isn't tuned well, the active guidance will go haywire. Sorry about that, there's little I can do about it at the moment. Would need a more complex atmospheric ascent guidance and unfortunately I don't have the time to develop it.

Regarding your other problems: I didn't know about number 1, as I've never tried to do something like this. It is definitely worth looking deeper into this. As for point 2, this is a known feature request - see #8.

**Comment by Patrykz94** [comment]
I'm pretty sure that number 1 is more of a KSP/kOS limitation rather than an issue with PEGAS.

For example, you can only use the `STAGE.` command on an active vessel, otherwise kOS will return an error. Another thing is that once an inactive vessel goes outside of the physics range ~20km away your active vessel, KSP will unload it and put it "on-rails" meaning kOS can no longer control it.

To go around this, if you want to reclaim the first stage, you could use the FMRS mod (Flight Manager for Reuseable Stages) which creates a save point whenever you stage. So you can finish the PEGAS mission as normal, then go back in time to moment of stage separation using FMRS, do what you need to do with the first stage and then come back to the main mission with upper stage.

**Comment by GYskyfall** [comment]
Maybe considering writing reentry procedures, or perfecting pegas for interstellar launches with gravity assitance，is another direction of development. 

Here is the link of  programs about flyby.
[https://forum.kerbalspaceprogram.com/index.php?/topic/131796-130-ascentdescent-addon-for-interplanetory-transfer-before-launch-planning-and-plads-flyby-finder-interface/#comment-2410285](url)
[https://forum.kerbalspaceprogram.com/index.php?/topic/73174-win-flyby-finder-v086-ksp13/&](url)
