### ISSUE TITLE
Use PEGAS in landing

### ISSUE THREAD

**Issue by GYskyfall** [Noiredd/PEGAS#27]
I want to use UPFG to achieve spaceX booster landing.

I have tried to directly change the existing pegas code but it did not succeed. I also read NASA's documentation and found that *Shepperd, S.W., Robertson. W. M., "Conic Required Velocity Determination", Space Shuttle GN&C Equation Document No. 26, Draper Laboratory 1973* is the key in landing mode.

Do you have this document, or can you give me some advice on how to write a landing code?

Also may I get your email address so that I can contact you directly

**Comment by Noiredd** [comment]
The same thought occurred to me soon after finishing PEGAS. The same math that computes a guidance solution to a dynamic state defined by an orbital plane, radius and velocity magnitude, should work for a solution constrained by radius equal to planet radius and velocity equal to linear rotation velocity at the given latitude, with plane adjusted so that these conditions actually mean a point stationary with respect to the planet surface. Whether the same algorithm would converge under such constraints is a question that perhaps would be better asked under [PEGAS-MATLAB](https://github.com/Noiredd/PEGAS-MATLAB) - this would need thorough testing in some artificial environment.

All this said, I haven't deeply investigated this possibility, so I won't be able to give you any direct help. I couldn't get my hands on document 26, the closest I have is 25, also by Shepperd and Robertson, *Conic State Extrapolation*. I'm also pretty sure it's not avaiable on [NTRS](https://ntrs.nasa.gov) - I looked and could only find docs 4, 17 and 19-23, and no other guidance-related documents by any "Robertson".  
Still, I could give you my email (although please don't expect any serious help - as I said, I haven't done any research on this, not to mention experimental work), if you can find a way for me to send it over privately. Ideas?

PS: apologies for a very late reply. I am currently very busy with other projects and, sadly, I admit I have neglected PEGAS. I will try to be more attentive of it in the future.

**Comment by alobazombie** [comment]
Hi, sorry to join in very late,

I think the "Conic Required Velocity Determination" routine can be found in an earlier document publicly available: 

19720018223 - SPACE SHUTTLE GUIDANCE, NAVIGATION AND CONTROL DESIGN EQUATIONS - VOLUME III ORBITAL OPERATIONS

specifically section 9.7.1.1

just wanted to pitch in as I've been looking for this routine for a while to enable Lambert ascents and on.orbit manoeuvres with UPFG, i.e. modes 3,7

**Comment by Noiredd** [comment]
I've always been thinking about using UPFG for general maneuvers and landing, but I honestly don't have time to develop any of this. Even if I ever find time (unlikely), this would not be a part of PEGAS (which is an _ascent autopilot_) but a whole another project.
