### ISSUE TITLE
PEGAS with Asparagus Staging

### ISSUE THREAD

**Issue by Jhorn1** [Noiredd/PEGAS#29]
I was just wondering if anyone has had any success with Asparagus staging. I have tried to do something like (mass 3*(1000000+7500000)) then after separation divide the thrust by 3 then add the difference of full tank to the amount left in the center stage. I have had no success with a lot of trial and error. Just wondering if anyone has tried to make a working script. Flying the Atlas heavy is not worth it unless you can Asparagus stage.

**Comment by Noiredd** [comment]
First of all, my sincere apologies for a very late reply. I am currently very busy with other projects and, sadly, I admit I have neglected PEGAS. I will try to be more attentive of it in the future.

Regarding the actual issue. Although I haven't tried myself, it **should already be possible to implement asparagus staging** in PEGAS - the only nuance is that you have to do (some of) the math yourself. Let's assume there is one core booster and `n` secondary boosters that will be jettisoned in pairs. For simplicity we will assume that those boosters are exactly same as the core booster - both in mass and engines (it's still doable if they differ, although with more math to work through). Since it's asparagus, all of the boosters are fed from the last two ("last" meaning: those that will be jettisoned next) -- the strong assumption is that whenever you stage, you drop two empty tanks, and all of the remaining tanks are fully fueled (as if the rocket was brand-new).  
Some symbols now:

* `Mt` -- total mass of the vehicle
* `Mb` -- total wet mass of each booster
* `Mf` -- mass of the fuel in each booster
* `Fb` -- thrust of a single booster

If we denote `Mr` as mass of the second stage (that is, rocket *after* the asparagus phase), then we can say that `Mt = Mr + (n + 1) * Mb`.

Defining the first stage is the crucial point in understanding this. Its total mass and engine setup will remain the same (as if you weren't doing asparagus) - the only difference will be in `massFuel`, since PEGAS calculates the staging time basing on this information. You want to drop the secondary boosters when *they* run out, so your `massFuel` is equal to `2 * Mf` (this is saying: hit `stage` when all of the engines burn through the fuel contained in the last two boosters). Your `engines` have `thrust` of `(n + 1) * Fb`.

The next stage will now be a fully-fueled rocket, just without two of the boosters - . `massTotal` is the old `Mt` minus `2 * Mb` and `massFuel` again is `2 * Mf` - after all, you want to stage after depleting the two boosters which are *now* the last ones. Of course, you have to modify the total engine thrust by subtracting the contribution of the two dropped ones: `thrust` will be equal to `(n - 1) * Fb` (initial count minus 2).  

For the final stage this is all slightly different. Since now you only have the core booster supporting the rest of the stack, your `massTotal` becomes `Mr + Mb` and `massFuel` is just `Mf` (only a single booster of fuel to burn). The `thrust` of your `engines` is also only `Fb` because you have the single core burning the fuel.

I hope this clears things up. For the less symmetric setup (i.e. your core booster has more/less engines than each of the jettisonable ones) you will probably have to use the full power of the `engines` system and define each booster as a separate engine, letting PEGAS do the thrust/mdot summation math. Possibly also the masses calculation will be a little different, but with this explanation I think you should be able to do this on your own.  
In case of any further questions, please reply in this thread and I'll try to give you any help I can.

**Comment by Jhorn1** [comment]
Thanks, I have found a really crude way of solving my problem by tricking the computer into thinking that the amount of fuel in the center stage is the amount gained from the outer boosters + the total fuel used in the center stage and it works fine. I will try and make a more refined version using actual algebra.
