### ISSUE TITLE
"Tried to push NaN into the stack

### ISSUE THREAD

**Issue by TheGrover** [Noiredd/PEGAS#4]
Getting a strange bug during launch. i had the procedure working correctly, and I don't know what i have done differently to bring on the bug.

Launch goes fine at first, atmospheric flight is normal, boosters drop and the guidance takes over shortly before first stage burnout, then just as the second stage lights, the third stage separates (igniting 3rd stage engines) causing a catastrophic failure at the top of the atmosphere.

Files attached:
Craft File, vehicle and mission plugs for the Pegas and image of the bug

![pegas bug](https://user-images.githubusercontent.com/31784291/30235665-fd97cbdc-9502-11e7-952e-f0d3ac3de9d8.png)
[Plugs.zip](https://github.com/Noiredd/PEGAS/files/1289438/Plugs.zip)
[Craft File.zip](https://github.com/Noiredd/PEGAS/files/1289440/Craft.File.zip)

Any help would be appreciated

**Comment by Noiredd** [comment]
1. Check your `sequence`. Your "jettison fairings" event actually activates the entire second stage. By removing the event from the sequence, the bug went away. Alternatively, you could move the fairings into an entirely new staging event (as in the VAB staging list), and place it in the right order.  
Explanation: things like `Tried to push Nan into the stack` happen when things that PEGAS sees are not what it expects - this often means mass which is smaller/larger than should be for the given stage, resulting in a negative argument in the logarithm somewhere in block 3 of the algorithm. Log of something negative is undefined, which in kOS means NaN, which cannot be pushed into a stack, hence the error.

2. Something is definitely off with (at least) one of the stages. From what I see, your `vehicle` looks good, but still the first stage burns for longer than it should, resulting in the second stage burning longer than it should, causing it to crash into the third stage (when PEGAS separates a stage that is still burning). I will research this in-depth tomorrow, as this might very well indicate a bug in the code.

**Comment by TheGrover** [comment]
Thanks for having a look

1) might be my install of KSP which seems to place my fairing into a main stages stage (in the stage list in the builder) every time I tweak the payload, should have noticed :p

2) don't know if it helps, but I've used a pretty standard install of RO-RSS. And besides TestFlight throwing some random failures in there, the only thing I can think of to cause stages to burn longer is realfuels (I think) which makes the thrust and fuel flow rate very slightly, which might average out as a lower thrust and therefore longer burn time?

I'm away from home for the week, but I can send you a complete mod list when I'm next step my PC if that helps

**Comment by Noiredd** [comment]
PEGAS was tested with RealFuels, the thrust variations tend to cancel out and aren't usually an issue (they average into nominal thrust in my experience). Regarding your modlist, I already figured it out (SXT and RP0 being ones I didn't have) - though it would be a good thing to mention them in the first post next time :)

**Comment by Noiredd** [comment]
0c96c47 changes several related things and I was able to get your vehicle to orbit after fixing the fairing jettison event. Third stage still ignited too early (while the second one was burning) which caused a collision, but somehow the vehicle recovered.

One thing I know for sure is that something is not right with your masses - please recheck your dry/wet numbers. Also, try aiming for a little higher orbit - 200x250km for example; PEGAS had to introduce a huge overshoot when aiming for the original 150x250 orbit.

I am closing the issue for now. Please get the newest version of PEGAS (you may need to download raw files or clone the repo, since this is not yet a release) and follow my advice - if you *still* have problems, don't hesitate to open this again (with updated `vehicle` files).
